# Copyright 2023 The CeresDB Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "df_engine_extensions"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
arrow = { workspace = true }
async-recursion = "1.0.4"
async-trait = { workspace = true }
catalog = { workspace = true, features = ["test"] }
ceresdbproto = { workspace = true }
common_types = { workspace = true, features = ["test"] }
datafusion = { workspace = true }
datafusion-proto = { workspace = true }
futures =   { workspace = true }
generic_error = { workspace = true }
lazy_static = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true }
snafu = { workspace = true }
table_engine = { workspace = true }
trace_metric = { workspace = true }

[dev-dependencies]
insta = { version = "1.31.0" }
tokio = { workspace = true }
